### ISSUE TITLE
Corrección tarea 7

### ISSUE THREAD

**Issue by davidamaro** [Giovanni-Alonso-Torres/Fisica_Computacional_Alonso_Torres#1]
Hola. Estaba hojeando tu tarea 7 y me dí cuenta que calculaste una __rectificación__ de los puntos, no una __interpolación__. Por favor, corríjelo antes de esta noche para que no te _penalice_, ya que esto a pesar de ser más complicado, __no__ es lo que se te pidió.

__Nota.__ es una curiosidad que me haya dado cuenta de esto antes de calificar, así que te sugiero que prestes más atención a lo que se te pide.

**Comment by Giovanni-Alonso-Torres** [comment]
Que yo sepa, mi rutina si esta correcta (pero ya la actualice dando más puntos), sólo que como a la curva del interpolador no le daba más puntos, entonces por eso parece que sólo es la unión de ellos, pero si se le dan más puntos, se observa una curva (el polinomio). Si esto no es a lo que te refieres, entonces no sé cual sea el error, según yo, mi rutina si arroja el interpolador, hasta se puede dar explícitamente sí, justo como lo pide el profesor, se evalúa en una variable simbólica. Y gracias por tomarte el tiempo para revisar antes.

**Comment by davidamaro** [comment]
@Giovanni-Alonso-Torres Gracias por añadir más puntos a la gráfica.
